use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    generate_md_extensions();
    tauri_build::build();
}

/// Reads the project-root `markdown-extensions.json` (the single source of
/// truth shared with the frontend at build time) and generates a Rust file
/// declaring `MD_EXTENSIONS` as a `&'static [&'static str]`. Both the parsing
/// and the const are baked into the binary at compile time — no runtime cost,
/// no LazyLock, no fallible serde call at first use.
fn generate_md_extensions() {
    let json_path = PathBuf::from("../markdown-extensions.json");
    let canonical = json_path.canonicalize().unwrap_or_else(|e| {
        panic!(
            "markdown-extensions.json not found at {} ({e}). It must live at the project root.",
            json_path.display()
        )
    });
    println!("cargo:rerun-if-changed={}", canonical.display());

    let json = fs::read_to_string(&canonical)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", canonical.display()));

    let extensions: Vec<String> = serde_json::from_str(&json)
        .unwrap_or_else(|e| panic!("invalid markdown-extensions.json: {e}"));

    if extensions.is_empty() {
        panic!("markdown-extensions.json is empty; need at least one extension");
    }

    // Validate everything is a plain ASCII extension (no leading dot, no slashes).
    for ext in &extensions {
        let valid = !ext.is_empty()
            && !ext.starts_with('.')
            && ext.chars().all(|c| c.is_ascii_alphanumeric());
        if !valid {
            panic!("invalid extension {ext:?} in markdown-extensions.json");
        }
    }

    let entries: Vec<String> = extensions.iter().map(|e| format!("    {e:?}")).collect();
    let generated = format!(
        "// Generated by build.rs from markdown-extensions.json — do not edit.\npub static MD_EXTENSIONS: &[&str] = &[\n{}\n];\n",
        entries.join(",\n")
    );

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is set by cargo"));
    let dest = out_dir.join("md_extensions.rs");
    fs::write(&dest, generated)
        .unwrap_or_else(|e| panic!("failed to write {}: {e}", dest.display()));
}
