use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    generate_md_extensions();
    embed_comctl32_v6_in_test_binaries();
    tauri_build::build();
}

/// Embed the ComCtl32 v6 (Common-Controls 6.0.0.0) manifest dependency when
/// linking on Windows.
///
/// Tauri embeds this manifest into the shipped `glyph.exe` so the modern
/// (WinSxS) ComCtl32 v6 is loaded. The cargo unit-test harness binary, however,
/// gets no such manifest, so it binds to the legacy System32 ComCtl32 v5.82 —
/// which lacks `TaskDialogIndirect`, a v6-only export that `rfd` (pulled in via
/// `tauri-plugin-dialog`) statically imports. The result is a load-time
/// `STATUS_ENTRYPOINT_NOT_FOUND` (0xc0000139) crash before any test runs.
///
/// `cargo:rustc-link-arg` is the only directive that reaches the lib unit-test
/// harness (the `-tests` variant covers `[[test]]` integration targets only,
/// which this crate has none of). It also applies to the shipped binary and the
/// cdylib, but both already declare (or are agnostic to) the v6 dependency, so
/// the duplicate is merged harmlessly by the linker.
fn embed_comctl32_v6_in_test_binaries() {
    if env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("windows") {
        println!(
            "cargo:rustc-link-arg=/MANIFESTDEPENDENCY:type='win32' \
             name='Microsoft.Windows.Common-Controls' version='6.0.0.0' \
             processorArchitecture='*' publicKeyToken='6595b64144ccf1df' language='*'"
        );
    }
}

/// Single source of truth for the supported markdown extensions:
/// `src-tauri/tauri.conf.json` → `bundle.fileAssociations[0].ext`.
///
/// That list is what the OS sees (Windows registry, macOS Info.plist, Linux
/// `.desktop` file) so anything not in it can't reach the app via file
/// association anyway. Reading it here keeps the Rust `is_markdown_file`
/// check, the frontend `isMarkdownFile` helper, and the OS file-association
/// registration in lockstep automatically.
///
/// Generates `MD_EXTENSIONS: &'static [&'static str]` at build time so there
/// is no runtime cost and no fallible serde call at first use.
fn generate_md_extensions() {
    let conf_path = PathBuf::from("tauri.conf.json");
    let canonical = conf_path
        .canonicalize()
        .unwrap_or_else(|e| panic!("tauri.conf.json not found at {} ({e})", conf_path.display()));
    println!("cargo:rerun-if-changed={}", canonical.display());

    let json = fs::read_to_string(&canonical)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", canonical.display()));

    let value: serde_json::Value =
        serde_json::from_str(&json).unwrap_or_else(|e| panic!("invalid tauri.conf.json: {e}"));

    let exts = value
        .get("bundle")
        .and_then(|b| b.get("fileAssociations"))
        .and_then(|fa| fa.as_array())
        .and_then(|arr| arr.first())
        .and_then(|first| first.get("ext"))
        .and_then(|ext| ext.as_array())
        .unwrap_or_else(|| {
            panic!(
                "tauri.conf.json is missing bundle.fileAssociations[0].ext — \
                 that array is the single source of truth for supported markdown extensions"
            )
        });

    let extensions: Vec<String> = exts
        .iter()
        .map(|v| {
            v.as_str()
                .unwrap_or_else(|| {
                    panic!("non-string entry in tauri.conf.json fileAssociations[0].ext")
                })
                .to_string()
        })
        .collect();

    if extensions.is_empty() {
        panic!(
            "tauri.conf.json bundle.fileAssociations[0].ext is empty; \
             need at least one extension"
        );
    }

    // Validate everything is a plain ASCII extension (no leading dot, no slashes).
    for ext in &extensions {
        let valid = !ext.is_empty()
            && !ext.starts_with('.')
            && ext.chars().all(|c| c.is_ascii_alphanumeric());
        if !valid {
            panic!("invalid extension {ext:?} in tauri.conf.json fileAssociations[0].ext");
        }
    }

    let entries: Vec<String> = extensions.iter().map(|e| format!("    {e:?}")).collect();
    let generated = format!(
        "// Generated by build.rs from tauri.conf.json — do not edit.\npub static MD_EXTENSIONS: &[&str] = &[\n{}\n];\n",
        entries.join(",\n")
    );

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is set by cargo"));
    let dest = out_dir.join("md_extensions.rs");
    fs::write(&dest, generated)
        .unwrap_or_else(|e| panic!("failed to write {}: {e}", dest.display()));
}
